### ISSUE TITLE
NuGet fails with fresh Unreal Engine 5.2 Project

### ISSUE THREAD

**Issue by zolrath** [axodox/axodox-machinelearning#2]
Hello!
Very excited for this project!

Attempting to add Axodox.Common via NuGet to an Unreal Engine 5 project fails with the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The expression "[System.IO.Directory]::GetFiles(P:\Unreal\TestProject\packages\Axodox.Common.1.0.14\build\native\..\..\lib\desktop\x64\Development_Editor, *.lib)" cannot be evaluated. Could not find a part of the path 'P:\Unreal\TestProject\packages\Axodox.Common.1.0.14\lib\desktop\x64\Development_Editor'.  P:\Unreal\TestProject\packages\Axodox.Common.1.0.14\build\native\Axodox.Common.targets

This is after setting the C++ standard to C++20 in visual studio as well as:
```
public class TestProject: ModuleRules
{
	public TestProject(ReadOnlyTargetRules Target) : base(Target)
	{
		CppStandard = CppStandardVersion.Cpp20
                ...
```

**Comment by zolrath** [comment]
For completeness sake, Unreal Engine doesn't actually support NuGet packages so this would need to be wrapped in an Unreal Engine Plugin for a Third Party Library.

**Comment by axodox** [comment]
Yes I am aware, I plan to create one in the coming weeks.
